### ISSUE TITLE
Redis 扩展问题，导致调用taf失败，通讯异常

### ISSUE THREAD

**Issue by Titanssword** [tangramor/docker-tars#109]
该Docker内部的redis扩展使用的是phpiredis，使用方式为，
```
$redis = phpiredis_connect('127.0.0.1', 6379);      // normal connection
```
对于[TarsActDemo](https://github.com/TarsPHP/TarsPHP/tree/master/examples/TarsActDemo)，该例子中使用的Redis的用法为
```
self::$redisInstance[$conf] = new Redis();
self::$redisInstance[$conf]->connect($config['host'], $config['port'], $config['timeout']);
```
这种用法为php的redis的官方扩展。

如果用该Docker直接去跑TarsActDemo，则会报错，
![image](https://user-images.githubusercontent.com/9337319/50628352-c5c19f80-0f72-11e9-9ef0-57d221e4132c.png)

经查log发现，错误为，
![image](https://user-images.githubusercontent.com/9337319/50628367-d40fbb80-0f72-11e9-82d2-f76e74695033.png)

建议补充php的官方Redis的扩展。

**Comment by tangramor** [comment]
已经添加了 php-pecl-redis4
